import Head from "next/head";
import { Navbar, Link, Text, Container, Spacer, Radio, useTheme } from "@nextui-org/react";
import { styled } from "@nextui-org/react";
// import styles from "@/styles/Home.module.css";

const Box = styled("div", {
  boxSizing: "border-box",
});

function About() {
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
      </Head>
      <Box css={{ px: "$12", mt: "$8", "@xsMax": { px: "$10" } }}>
        <Container>
          <Text size="$xl">
            As a student leader with an insatiable appetite for learning new technology and business expertise, I am an aspiring computer scientist set to
            graduate from{" "}
            <a
              target="_blank"
              href="https://vt.edu">
              Virginia Tech
            </a>{" "}
            in May of 2025. I lead and serve my community as an Eagle Scout and as a directing member of the{" "}
            <a
              target="_blank"
              href="https://sec.vt.edu">
              Student Engineers Council at Virginia Tech
            </a>{" "}
            , I oversee a 501(c)(3) nonprofit with $800k+ in annual revenue, manage a team of 20+ student engineers, and work with the university to improve the
            student experience. I am a results-driven mobile application developer with four years of experience in Swift (iOS), Flutter, and React. One of my
            notable projects is an app designed to assist Speech Pathologists with their clinical assessments, receiving over 800 downloads in its first week. I
            also have experience coding in Java and Python, as well as deploying application backend on AWS and Google Firebase. Additionally, I have hands-on
            expertise in 3D prototyping, robotics design and fabrication, and Computer-Aided Design (CAD). Most recently I had internship last summer working on
            mobile SDK for a fraud detection and analysis product. I am now doing research for the VT computer science department on their CSGenome project,
            which researches and catalogs different computer systems. I am currently looking for an internship or contract software engineering position
            starting in May of 2023.
          </Text>
          <Text size="$xl">
            If you are interested in working with me, please feel free to <Link href="mailto:collind@vt.edu"> contact me</Link>.
          </Text>
        </Container>
      </Box>
    </>
  );
}

export default About;
