import Banner from './banner'

export const metadata = {
  title: 'Contact',
  description: 'Generated by create next app',
}
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Banner />
      {children}
    </>
  )
}
