import { Inter } from 'next/font/google'
import './globals.css'
import NavHeader from './_header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Ballygorey',
    template: `%s | Ballygorey`,
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en-US">
      <head>
        <meta name="theme-color" content="teal"></meta>
      </head>
      <body>
        <NavHeader />
        {children}
      </body>
    </html>
  )
}
